"use client";
import { useEffect, useState } from "react";
import { api, type StrDeal, type StrResults, type StrScenario } from "@/lib/api";
import { Panel, WorkspaceIntro } from "@/components/ProductUI";
const base:StrDeal={name:"Northeast cabin",address:"Lake Harmony, PA",strategy:"investment",property_price:350000,down_payment_pct:.25,mortgage_apr:.08,loan_term_years:30,closing_cost_pct:.05,furnishings:25000,cash_reserve:15000,annual_gross_revenue:60000,revenue_source:"assumption",forecast_as_of:null,comparable_count:0,monthly_gross_revenue:null,owner_nights:0,owner_nights_by_month:null,property_tax_annual:6000,insurance_annual:3600,utilities_annual:4800,property_services_annual:2500,repairs_capex_annual:5000,management_pct:.20,platform_pct:.08,turnovers_pct:.12,regulatory_gate:"unknown",hoa_gate:"unknown",refinance_after_months:24,refinance_apr:.055,refinance_fees:0};
const fmt=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const numericFields: [keyof StrDeal,string,boolean?][]=[["property_price","Purchase price"],["down_payment_pct","Down payment",true],["mortgage_apr","Mortgage rate",true],["closing_cost_pct","Closing and transfer taxes",true],["furnishings","Furniture / setup"],["cash_reserve","Retained reserve"],["annual_gross_revenue","Gross annual bookings"],["owner_nights","Personal nights"],["property_tax_annual","Annual property tax"],["insurance_annual","Annual insurance"],["utilities_annual","Annual utilities"],["property_services_annual","Snow / landscaping"],["repairs_capex_annual","Maintenance and capex"],["management_pct","Manager fee",true],["platform_pct","Platform fee",true],["turnovers_pct","Cleaning and supplies",true],["refinance_apr","Future refinance rate",true],["refinance_after_months","Refinance after months"],["refinance_fees","Refinance fees"],["comparable_count","Comparable rentals"]];
export function ShortStayWorkspace(){
 const [deal,setDeal]=useState<StrDeal>(base);const [result,setResult]=useState<StrResults|null>(null);const [saved,setSaved]=useState<StrScenario[]>([]);const [selected,setSelected]=useState("");const [error,setError]=useState("");
 useEffect(()=>{api.strScenarios().then(setSaved).catch(()=>{});},[]);
 useEffect(()=>{const t=setTimeout(()=>{api.underwriteStr(deal).then(r=>{setResult(r);setError("");}).catch(e=>{setResult(null);setError(String(e));});},300);return()=>clearTimeout(t);},[deal]);
 const change=<K extends keyof StrDeal>(k:K,v:StrDeal[K])=>setDeal(d=>({...d,[k]:v}));
 async function persist(){try{const x=selected?await api.updateStrScenario(selected,{name:deal.name,deal}):await api.saveStrScenario({name:deal.name,deal});setSelected(x.id);setSaved(await api.strScenarios());}catch(e){setError(String(e));}}
 return <main className="mx-auto max-w-[1440px] space-y-6 px-4 py-8"><WorkspaceIntro eyebrow="Investment research" title="Short-term rental underwriting" description="Model investment cabins or personal-use hybrids across the Northeast. All assumptions remain research-only until property-specific evidence and legal permissions are verified."/>
 <div className="grid gap-5 lg:grid-cols-[3fr_2fr]"><div className="space-y-5"><Panel className="space-y-4 p-5"><h2 className="font-semibold">Scenario and property</h2>
 <select className="w-full rounded-lg border p-2" value={selected} onChange={e=>{setSelected(e.target.value);const x=saved.find(x=>x.id===e.target.value);if(x)setDeal(x.deal);}}><option value="">New scenario</option>{saved.map(s=><option key={s.id} value={s.id}>{s.name}: {s.deal.address}</option>)}</select>
 {(["name","address"] as const).map(k=><label key={k} className="block text-sm">{k}<input className="mt-1 w-full rounded-lg border p-2" value={deal[k]} onChange={e=>change(k,e.target.value)}/></label>)}
 <div className="flex gap-2"><button className="primary-button" onClick={()=>void persist()}>{selected?"Update":"Save"} scenario</button><button className="rounded-lg border p-2 text-sm" onClick={()=>{setSelected("");setDeal(base);}}>New</button></div></Panel>
 <Panel className="space-y-4 p-5"><h2 className="font-semibold">Economics and operations</h2>
 <label className="block text-sm">Ownership purpose<select className="mt-1 w-full rounded-lg border p-2" value={deal.strategy} onChange={e=>setDeal(d=>({...d,strategy:e.target.value as StrDeal["strategy"],owner_nights:0,owner_nights_by_month:null}))}><option value="investment">Investment-first</option><option value="hybrid">Hybrid personal use</option></select></label>
 <div className="grid gap-3 sm:grid-cols-2">{numericFields.filter(([key])=>deal.strategy==="hybrid"||key!=="owner_nights").map(([key,label,pct])=><label className="text-xs font-medium text-slate-600" key={key}>{label}{pct?" (%)":" ($ or count)"}<input type="number" min="0" step={pct?".25":"1"} className="mt-1 w-full rounded-lg border p-2 text-sm" value={Number(deal[key])*(pct?100:1)} onChange={e=>change(key,Number(e.target.value)/(pct?100:1) as never)}/></label>)}</div>
 <label className="block text-sm">Revenue provenance<select className="mt-1 w-full rounded-lg border p-2" value={deal.revenue_source} onChange={e=>change("revenue_source",e.target.value as StrDeal["revenue_source"])}><option value="assumption">Assumption</option><option value="market_average">Market average (NOT property-specific)</option><option value="licensed_property_forecast">Licensed property-level forecast</option><option value="actual_operations">Actual operations</option></select></label>
 <label className="block text-sm">Forecast date<input type="date" className="mt-1 w-full rounded-lg border p-2" value={deal.forecast_as_of??""} onChange={e=>change("forecast_as_of",e.target.value||null)}/></label>
 <div className="grid grid-cols-3 gap-2">{Array.from({length:12},(_,i)=>{const values=deal.monthly_gross_revenue??Array(12).fill(deal.annual_gross_revenue/12);const nights=deal.owner_nights_by_month??Array(12).fill(0);return <div key={i} className="rounded-lg border p-2"><p className="text-xs">{new Date(2026,i,1).toLocaleString("en-US",{month:"short"})}</p><input aria-label={"Revenue month "+i} type="number" className="w-full text-xs" value={Math.round(values[i])} onChange={e=>{const x=[...values];x[i]=Number(e.target.value);change("monthly_gross_revenue",x);}}/>{deal.strategy==="hybrid"&&<><span className="text-[10px]">Owner nights</span><input aria-label={"Owner nights month "+i} type="number" className="w-full text-xs" value={nights[i]} onChange={e=>{const x=[...nights];x[i]=Number(e.target.value);setDeal(d=>({...d,owner_nights_by_month:x,owner_nights:x.reduce((a,b)=>a+b,0)}));}}/></>}</div>})}</div><button className="rounded-lg border p-2 text-xs" onClick={()=>change("monthly_gross_revenue",null)}>Clear monthly forecast</button></Panel>
 <Panel className="space-y-3 p-5"><h2 className="font-semibold">Property-level regulation gates</h2>{(["regulatory_gate","hoa_gate"] as const).map(k=><label className="block text-sm" key={k}>{k}<select className="mt-1 w-full rounded-lg border p-2" value={deal[k]} onChange={e=>change(k,e.target.value as StrDeal[typeof k])}><option value="unknown">Not verified</option><option value="verified">Verified in writing</option><option value="blocked">Blocked</option></select></label>)}</Panel></div>
 <div className="space-y-5"><Panel className="space-y-4 p-5"><h2 className="font-semibold">Underwriting results</h2>{error&&<p className="text-sm text-red-700">{error}</p>}{result&&<><div className="rounded-xl bg-slate-100 p-4"><p className="text-xs">Annual cash flow after mortgage</p><p className="text-3xl font-bold">{fmt(result.annual_cash_flow)}</p><p className="text-xs">{result.screening_status.replaceAll("_"," ")}</p></div><div className="grid grid-cols-2 gap-4">{([["Gross after personal use",fmt(result.annual_gross_after_owner_use)],["Foregone rent",fmt(result.foregone_owner_revenue)],["NOI",fmt(result.annual_noi)],["Debt service",fmt(result.annual_debt_service)],["Invested + reserves",fmt(result.capital_required_including_reserves)],["Cash-on-cash",(result.cash_on_cash*100).toFixed(1)+"%"],["DSCR",result.debt_service_coverage?.toFixed(2)??"Cash"],["−20% bookings",fmt(result.downside_cash_flow)],["Cash-flow breakeven",fmt(result.break_even_gross_before_owner_use)],["Future refinance cash flow",fmt(result.future_refinanced_annual_cash_flow)]] as const).map(([k,v])=><div key={k}><p className="text-xs text-slate-500">{k}</p><p className="font-semibold">{v}</p></div>)}</div></>}</Panel>{result&&<Panel className="space-y-2 p-5"><h2 className="font-semibold">Evidence and limitations</h2>{result.warnings.map((w,i)=><p className="text-sm text-slate-600" key={i}>• {w}</p>)}</Panel>}</div></div></main>;
}
